-- MySQL Script generated by MySQL Workbench
-- Sat Feb 27 19:06:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema online-store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online-store` DEFAULT CHARACTER SET utf8 ;
USE `online-store` ;

-- -----------------------------------------------------
-- Table `online-store`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`roles` (
  `r_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `r_name` VARCHAR(45) NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`users` (
  `u_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_login` VARCHAR(50) NOT NULL,
  `u_password` VARCHAR(20) NOT NULL,
  `u_email` VARCHAR(150) NOT NULL,
  `u_role` INT UNSIGNED NULL COMMENT 'У пользователя может быть только 1 роль - либо администратор, либо клиент',
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `UNQ_u_login` (`u_login` ASC) VISIBLE,
  UNIQUE INDEX `UNQ_u_email` (`u_email` ASC) INVISIBLE,
  INDEX `UNQ_role` (`u_role` ASC) INVISIBLE,
  CONSTRAINT `FK_user_role`
    FOREIGN KEY (`u_role`)
    REFERENCES `online-store`.`roles` (`r_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`categories` (
  `c_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `IDX_c_name` (`c_name` ASC) VISIBLE,
  UNIQUE INDEX `c_name_UNIQUE` (`c_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`products` (
  `p_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `p_name` VARCHAR(45) NOT NULL,
  `p_picture_path` VARCHAR(255) NULL,
  `p_description` VARCHAR(2000) NULL,
  `p_price` DECIMAL(10,2) NULL,
  `p_rating` DECIMAL(3,2) NULL,
  `p_category` INT UNSIGNED NULL,
  PRIMARY KEY (`p_id`),
  UNIQUE INDEX `UNQ_p_id` (`p_id` ASC) INVISIBLE,
  INDEX `IDX_product_name` (`p_name` ASC) INVISIBLE,
  INDEX `IDX_product_price` (`p_price` ASC) VISIBLE,
  INDEX `FK_product_category_idx` (`p_category` ASC) VISIBLE,
  CONSTRAINT `FK_product_category`
    FOREIGN KEY (`p_category`)
    REFERENCES `online-store`.`categories` (`c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`order_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`order_statuses` (
  `os_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `os_description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`os_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`orders` (
  `o_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `o_user_id` INT UNSIGNED NOT NULL,
  `o_confirmation_date` TIMESTAMP(6) NULL,
  `o_ready_date` TIMESTAMP(6) NULL,
  `o_status` INT UNSIGNED NULL,
  PRIMARY KEY (`o_id`),
  INDEX `FK_order_user` (`o_user_id` ASC) INVISIBLE,
  INDEX `IDX_product_date` (`o_confirmation_date` ASC) INVISIBLE,
  INDEX `IDX_user_product` (`o_user_id` ASC, `o_confirmation_date` ASC) VISIBLE,
  INDEX `fk_orders_order_statuses1_idx` (`o_status` ASC) VISIBLE,
  CONSTRAINT `FK_order_user_id`
    FOREIGN KEY (`o_user_id`)
    REFERENCES `online-store`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_order_statuses1`
    FOREIGN KEY (`o_status`)
    REFERENCES `online-store`.`order_statuses` (`os_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`m2m_order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`m2m_order_product` (
  `op_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `op_order` INT UNSIGNED NOT NULL,
  `op_product` INT UNSIGNED NOT NULL,
  `op_number_of_products` INT UNSIGNED NOT NULL,
  INDEX `IDX_order_product_product` (`op_product` ASC) VISIBLE,
  PRIMARY KEY (`op_id`),
  CONSTRAINT `FK_order_product_order`
    FOREIGN KEY (`op_order`)
    REFERENCES `online-store`.`orders` (`o_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_order_product_product`
    FOREIGN KEY (`op_product`)
    REFERENCES `online-store`.`products` (`p_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`banned_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`banned_users` (
  `b_user` INT UNSIGNED NOT NULL,
  `b_is_permanent` TINYINT NOT NULL,
  PRIMARY KEY (`b_user`),
  CONSTRAINT `FK_banned_users_user`
    FOREIGN KEY (`b_user`)
    REFERENCES `online-store`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online-store`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`user_details` (
  `ud_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ud_users_id` INT UNSIGNED NOT NULL,
  `ud_first_name` VARCHAR(100) NULL,
  `ud_last_name` VARCHAR(100) NULL,
  `ud_city` VARCHAR(100) NULL,
  `ud_phone` VARCHAR(25) NULL,
  `ud_adress` VARCHAR(500) NULL,
  PRIMARY KEY (`ud_id`, `ud_users_id`),
  UNIQUE INDEX `ud_phone_UNIQUE` (`ud_phone` ASC) VISIBLE,
  INDEX `fk_user_details_users1_idx` (`ud_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_ususersuserser_details_users1`
    FOREIGN KEY (`ud_users_id`)
    REFERENCES `online-store`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- ---------------users--------------------------------------
-- Table `online-store`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`deliveries` (
  `d_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `d_date` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`d_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`m2m_products_deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`m2m_products_deliveries` (
  `pd_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pd_delivery_id` INT UNSIGNED NOT NULL,
  `pd_product_id` INT UNSIGNED NOT NULL,
  `pd_number_of_products` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pd_id`),
  INDEX `fk_m2m_products_deliveries_products1_idx` (`pd_product_id` ASC) VISIBLE,
  INDEX `fk_m2m_products_deliveries_deliveries1_idx` (`pd_delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_m2m_products_deliveries_products1`
    FOREIGN KEY (`pd_product_id`)
    REFERENCES `online-store`.`products` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_m2m_products_deliveries_deliveries1`
    FOREIGN KEY (`pd_delivery_id`)
    REFERENCES `online-store`.`deliveries` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`products_at_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`products_at_store` (
  `pas_product_id` INT UNSIGNED NOT NULL,
  `pas_number_of_products` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pas_product_id`),
  INDEX `fk_products_at_store_products1_idx` (`pas_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_at_store_products1`
    FOREIGN KEY (`pas_product_id`)
    REFERENCES `online-store`.`products` (`p_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
