package by.tc.shop.controller.command;

public enum CommandName {
    AUTHORIZATION, GOTOREGISTRATIONPAGE, SAVENEWUSER, GOTOMAINPAGE,
    LOGOUT, GOTOAUTHORIZATIONPAGE, CHANGELOCALE, GOTOCARTPAGE, GOTOADDPRODUCTPAGE, GOTOCATEGORYPAGE,
    SAVENEWORDER, EDITPRODUCTAMOUNT, DELETEORDERITEM, CONFIRMORDER, GOTOACTIVEORDERSPAGE, SAVEUSERDETAILS, GOTOACTIVEORDERSINFOPAGE,
    VIEWALLCLIENTS, VIEWUSERDETAILS, BANUSER, DELETEORDER, VIEWBANNEDCLIENTS, UNBANUSER, UPDATEORDERREADYDATE, VIEWORDERSBYSTATUS, ADDPRODUCT,
    GOTOUSERDETAILSPAGE, DELETEPRODUCT, GOTODELIVERYPAGE, GOTODELIVERYNUMBERPAGE, SAVEDELIVERYITEM
}
